# Generated by Django 3.2.12 on 2022-03-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('num_to_unlock', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.tier')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedPuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'puzzle')},
            },
        ),
    ]
